# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ecma-re-validator/all/ecma-re-validator.rbi
#
# ecma-re-validator-0.2.1

module EcmaReValidator
  def self.valid?(input); end
end
