# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/leftovers/all/leftovers.rbi
#
# leftovers-0.4.2

module Leftovers
  def collector; end
  def config; end
  def each_or_self(value, &block); end
  def error(message); end
  def exit(status = nil); end
  def leftovers; end
  def newline; end
  def print(message); end
  def puts(message); end
  def pwd; end
  def reporter; end
  def reset; end
  def run(stdout: nil, stderr: nil); end
  def self.collector; end
  def self.config; end
  def self.each_or_self(value, &block); end
  def self.error(message); end
  def self.exit(status = nil); end
  def self.leftovers; end
  def self.newline; end
  def self.parallel; end
  def self.parallel=(arg0); end
  def self.parallel?; end
  def self.print(message); end
  def self.progress; end
  def self.progress=(arg0); end
  def self.progress?; end
  def self.puts(message); end
  def self.pwd; end
  def self.reporter; end
  def self.reset; end
  def self.run(stdout: nil, stderr: nil); end
  def self.stderr; end
  def self.stdout; end
  def self.try_require(requirable, message: nil); end
  def self.warn(message); end
  def stderr; end
  def stdout; end
  def try_require(requirable, message: nil); end
  def warn(message); end
end
class Leftovers::Error < StandardError
end
